### ISSUE TITLE
After build, ISV DLL's are not included in CommerceRuntime.ext.config or web.config

### ISSUE THREAD

**Issue by halcyonquest** [microsoft/Dynamics365Commerce.ScaleUnit#7] opened 2022-01-11 20:32 UTC
I am using release 9.31

I have to add several dll's from an ISV. I have tried multiple configurations, but nothing so far causes them to be included in the config files. The only files included are the assemblies built from project references.

The best I've been able to do so far is to create a separate project with just those dll's added as a reference. As long as I check the option to copy local, they will be dropped into the ext folder, but not included in the config file.

You can see below that the files are in the ext directory
![image](https://user-images.githubusercontent.com/60713084/149016615-616ec8b3-7104-4a25-abcb-9e8efc6a8f76.png)

But only the assemblies built by my project are in the configs
![image](https://user-images.githubusercontent.com/60713084/149016771-76b017c5-49d0-4fb9-8f74-ca74c3a2be56.png)

How can I get those files to be included?

**Comment by Pikhulya** [comment] 2022-01-14 22:12
If those DLLs do not contain public CRT/RS extensions, for instance, Controllers, Request Handlers, Triggers and so on, it is by design they are not included into the configuration files as those files should only reference assemblies containing the extensions recognized by CRT/RS. If an extension depends on another assembly, which doesn't have any CRT/RS artifacts - those are included into the extension package along with the rest of extension DLLs.

**Comment by halcyonquest** [comment] 2022-01-15 23:24
I actually have both kinds; CRT/RS dll's and supporting dll's. These dll's were provided by a third party ISV.

After doing some digging, I was able to make it work by opening the CommerceRuntime .csproj file and adding these tags
![image](https://user-images.githubusercontent.com/60713084/149640773-704e102b-aa64-415f-9276-d87d44c3838c.png)

In my project I created the two referenced folders and put the dlls in there. This does exactly what I want, but I would like to know if this is an acceptable (supported) solution or if there is a different way to do it. So now, any other ISV dlls just have to be added to the correct folder depending on whether or not it is a CRT or supporting dll.

**Comment by lukedgr** [comment] 2022-02-28 21:50
To better support the scenario described in this issue we have added support to automatically merge CSU packages in the Commerce SDK. Starting in the latest versions of 9.34 CSU cloud packages can be automatically merged using NuGet package references. To enable this the ISV should simply produce a NuGet package with their CSU deployable package using the GeneratePackageOnBuild flag on the project file. Then SI/Partner CSU project can package reference the NuGet package to automatically merge the ISV extensions.

Example
ISV Project File
![image](https://user-images.githubusercontent.com/3270455/156064064-a5111c75-168b-45fc-8a5e-a08ce70c4bec.png)


SI/Partner/Customer Scale Unit Project File
![image](https://user-images.githubusercontent.com/3270455/156064127-4786ec49-96a9-45eb-8fe8-d40c0e9497aa.png)

**Closed by lukedgr** 2022-02-28 21:50 UTC

**Comment by paksa07** [comment] 2022-12-09 08:08
Hi,
I have created a nuget package of an external DLL and added it scaleunit project. It is not adding the commerceruntime.ext.config file after build/rebuild.
